// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentEngine.Infrastructure.DataAccess;

namespace PaymentEngine.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentEngineContext))]
    partial class PaymentEngineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentEngine.Domain.Models.Payments", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CardHolder")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreditCardNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SecurityCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasFilter("[Reference] IS NOT NULL");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PaymentEngine.Domain.Models.Payments", b =>
                {
                    b.OwnsOne("PaymentEngine.Domain.Models.PaymentState", "PaymentState", b1 =>
                        {
                            b1.Property<long>("PaymentsId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Name")
                                .HasColumnType("int");

                            b1.HasKey("PaymentsId");

                            b1.ToTable("PaymentState");

                            b1.WithOwner()
                                .HasForeignKey("PaymentsId");
                        });

                    b.Navigation("PaymentState");
                });
#pragma warning restore 612, 618
        }
    }
}
